### ISSUE TITLE
Límite en el número de caracteres de los comentarios

### ISSUE THREAD

**Issue by joker-x** [podemos-info/participacion#14]
Actualmente está fijado a 1000. Está hardcodeado en el modelo Comment en el método body_max_length: https://github.com/podemos-info/participacion/blob/master/app/models/comment.rb#L87

Debemos convertir este valor en un dato configurable (en settings por ejemplo) y elegir qué nuevo límite poner en los comentarios.

**Comment by AritzaSm** [comment]
El límite de caracteres en plazaPodemos en reddit es de 15.000 Con modificar el valor actual para dejarlo en 15.000 sería suficiente.

**Comment by joker-x** [comment]
TODO: Hacer este valor configurable desde el admin.
