### ISSUE TITLE
Sistema para destacar determinados envíos

### ISSUE THREAD

**Issue by AritzaSm** [podemos-info/participacion#26]
- Los Administradores necesitarían la opción de de dejar arriba _"stickeado"_ uno o dos hilos, para que la gente cuando entre en las diferentes secciones los vea. ( la típica chincheta ) 
- En paralelo estaría bien contar con la opción de destacar los envíos de los administradores, con color de letra diferente, así se vería que es una respuesta oficial,  propongo morado ; )

**Comment by ggalancs** [comment]
Estaba ya desarrollado en la aplicación original, sólo hacia falta configurar el usuario con la opción correspondiente
