### ISSUE TITLE
al intentar ejecutar la consola de Rails sale el error: `mkdir': Permission denied @ dir_s_mkdir - /run/user/0/spring-1004 (Errno::EACCES)

### ISSUE THREAD

**Issue by ggalancs** [podemos-info/participacion#27]
al intentar ejecutar la consola de Rails sale el error: `mkdir': Permission denied @ dir_s_mkdir - /run/user/0/spring-1004 (Errno::EACCES)

**Comment by joker-x** [comment]
Ejecutar con el usuario correspondiente:

```
unset XDG_RUNTIME_DIR
```

de https://stackoverflow.com/questions/28174437/spring-permission-error-ubuntu-14-04/30181641#30181641?newreg=8ce29bac20c143a3b853466425faff20
